src/Entity/Piece.php
<?php

namespace App\Entity;

use App\Repository\PieceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PieceRepository::class)
 * @Vich\Uploadable
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="style", type="string")
 * @ORM\DiscriminatorMap(
 *      {
 *          "contemporaryart" = "App\Entity\PieceType\ContemporaryArt",
 *          "digitalart" = "App\Entity\PieceType\DigitalArt",
 *          "streetart" = "App\Entity\PieceType\StreetArt",
 *          "photography" = "App\Entity\PieceType\Photography"
 *      })
 */
abstract class Piece
{
    const ContemporaryArt = "ContemporaryArt";
    const DigitalArt  = "DigitalArt";
    const Photography = "Photography";
    const StreetArt  = "StreetArt";
    abstract public function getstyle();
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $artist;



    /**
     * @ORM\Column(type="boolean")
     */
    private $availability;

    /**
     * @ORM\ManyToOne(targetEntity=Owner::class, inversedBy="pieces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @ORM\ManyToMany(targetEntity=RentingDetail::class, mappedBy="piece")
     */
    private $rentingDetails;



    ///UPLOAD images des oeuvres

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="pieces_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    ///UPLOAD updated at

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    public $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $size;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $materialsTechnique;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $creationDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Price;



    public function __construct()
    {
        $this->rentingDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getArtist(): ?string
    {
        return $this->artist;
    }

    public function setArtist(string $artist): self
    {
        $this->artist = $artist;

        return $this;
    }



    public function getAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(bool $availability): self
    {
        $this->availability = $availability;

        return $this;
    }

    public function getOwner(): ?Owner
    {
        return $this->owner;
    }

    public function setOwner(?Owner $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return Collection|RentingDetail[]
     */
    public function getRentingDetails(): Collection
    {
        return $this->rentingDetails;
    }

    public function addRentingDetail(RentingDetail $rentingDetail): self
    {
        if (!$this->rentingDetails->contains($rentingDetail)) {
            $this->rentingDetails[] = $rentingDetail;
            $rentingDetail->addPiece($this);
        }

        return $this;
    }

    public function removeRentingDetail(RentingDetail $rentingDetail): self
    {
        if ($this->rentingDetails->removeElement($rentingDetail)) {
            $rentingDetail->removePiece($this);
        }

        return $this;
    }
//////


    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMaterialsTechnique(): ?string
    {
        return $this->materialsTechnique;
    }

    public function setMaterialsTechnique(?string $materialsTechnique): self
    {
        $this->materialsTechnique = $materialsTechnique;

        return $this;
    }

    public function getCreationDate(): ?int
    {
        return $this->creationDate;
    }

    public function setCreationDate(?int $creationDate): self
    {
        $this->creationDate = $creationDate;

        return $this;
    }


    public function formatedForView()
    {
        return [
            "title" => $this->getTitle(),
            "id" => $this->getId(),
            "image" => $this->getImage(),
            "description" => $this->getDescription(),
            "artist" => $this->getArtist(),
            "style" => $this->getStyle(),
            "size" => $this->getSize(),
            "creationDate" => $this->getCreationDate(),
            "materialsTechnique" => $this->getMaterialsTechnique(),
            "owner" => $this->getOwner(),
            


        ];
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(?int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }
}

src/Controller/ShowRentingController.php
<?php


namespace App\Controller;

use App\Entity\User;
use App\Entity\Renting;
use App\Form\RentingType;
use App\Form\RentingDetailType;
use App\Repository\RentingRepository;
use App\Repository\RentingDetailRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShowRentingController extends AbstractController
{
    /* #[Route('/show/renting/{id}', name: 'show_renting', methods: ['GET'])] */
    /**
     * @Route("/show/renting/{id}", name="show_renting", methods={"GET"})
     */
    public function index(EntityManagerInterface $entityManager, $id): Response
    {
        $user = $this->getUser();
        $renting = $entityManager->getRepository(Renting::class)->find($id);
        return $this->render('show_renting/index.html.twig', [
            'user' => $user,            
            'rentings' => $user->getRentings(),
            'renting' => $renting,
        ]);
    }
}

templates/show_renting/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ShowRentingController!{% endblock %}

{% block body %}

<div class="show-renting container">

    <h2>Détail de ta réservation nº {{ renting.id }}</h2>

        <ul>
            <li>Date de la commande : {{ renting.date ? renting.date|date('d-m-Y') : '' }}</li> 

            {% if renting.statuts == "pending" %}
                <li>En cours de préparation</li> 
            {% elseif renting.statuts == "shipped" %}
                <li>En cours de livraison</li> 
            {% else %}
                <li>Terminée</li> 
            {% endif %}


            {% for rentingDetail in renting.rentingDetails %}
                {# {{ dump(rentingDetail) }} #}

                <li><strong>Total de la commande : {{ rentingDetail.priceOption }} </strong></li>
        </ul>   

        <table class="table">
            <thead>
                <tr>
                    <th>Nom de l'oeuvre</th>                    
                    <th>Aperçu</th>
                    <th>Nom de l'artiste</th>
                    <th>Style</th>
                    <th>Prix par mois</th>
                </tr>
            </thead>

            <tbody>

                {% for piece in rentingDetail.piece %}
                    {# {{ dump(piece) }} #}
                    <tr>
                        <td>{{ piece.title }}</td>
                        <td><img src="{{ findmyart_display_image(piece, 'imageFile') }}" alt="{{ piece.title }}" /></td>
                        <td>{{ piece.artist }}</td>
                        
                        {% if piece.style == "Photography" %}
                            <td>Photographie</td>
                        {% elseif piece.style == "DigitalArt" %}
                            <td>Art Digital</td>
                        {% elseif piece.style == "ContemporaryArt" %}
                            <td>Art Contemporain</td>
                        {% else %}
                            <td>Street Art</td>
                        {% endif %}
                        
                        <td>{{ piece.price }} €</td>
                    </tr>
                {% endfor %}    

            </tbody>
        </table>
        {% endfor %}

        <div class="bouton">
                <a href="{{path('user_account')}}"><i class="fas fa-arrow-alt-circle-left m-2"></i>Retour à l'espace personnel</a>
        </div>

</div>
{% endblock %}